/******************************************************
 * PLEASE DO NOT EDIT THIS FILE
 * the verification process may break
 ******************************************************/

const bGround = require('fcc-express-bground');
const myApp = require('./myApp'); // Tu aplicación de Express exportada desde myApp.js
const express = require('express');

if (!process.env.DISABLE_XORIGIN) {
  myApp.use((req, res, next) => {
    const allowedOrigins = ['https://narrow-plane.gomix.me', 'https://www.freecodecamp.com'];
    const origin = req.headers.origin || '*';
    if (!process.env.XORIG_RESTRICT || allowedOrigins.indexOf(origin) > -1) {
      console.log(origin);
      res.setHeader('Access-Control-Allow-Origin', origin);
      res.header("Access-Control-Allow-Headers", "Origin, X-Requested-With, Content-Type, Accept");
    }
    next();
  });
}

const port = process.env.PORT || 3000;

bGround.setupBackgroundApp(express(), myApp, __dirname).listen(port, () => {
  bGround.log(`Node is listening on port ${port}...`);
});

/******************************************************
 * PLEASE DO NOT EDIT THIS FILE
 * the verification process may break
 ******************************************************/
